import Attendance from "./attendance.svg"
import ClassIcon from "./class.svg"
import Close from "./close.svg"
import Dashboard from "./dashboard.svg"
import Discipline from "./discipline.svg"
import Doubts from "./doubts.svg"
import Download from "./download.svg"
import Icon from "./icon.svg"
import LeftArrow from "./left-arrow.svg"
import RighrArrow from "./right-arrow.svg"
import Logout from "./logout.svg"
import Message from "./messages.svg"
import Notification from "./notification.svg"
import Notes from "./notes.svg"
import Notify from "./notify.svg"
import Report from "./report.svg"
import Search from "./search.svg"
import Setting from "./setting.svg"
import Schedule from "./schedule.svg"
import test from "./test.svg"
import Library from "./book.svg"
import Video from "./video.svg"
import FavChart from "./fav-chart.svg"
import Edit from "./edit.svg"
import Trash from "./trash.svg"


export { Attendance, Edit,Library ,Trash, Video, FavChart, ClassIcon, Close, Dashboard, Discipline, Doubts, Download, Icon, LeftArrow, RighrArrow, Logout, Message, Notification, Notes, Notify, Report, Search, Setting, Schedule, test }


